### ISSUE TITLE
is this for kotlin native is available？

### ISSUE THREAD

**Issue by jiqimaogou** [JetBrains/skiko#80]

**Comment by olonho** [comment]
Not yet.

**Comment by icode** [comment]
@olonho  Do you have a plan?

**Comment by anidotnet** [comment]
It would perfectly make sense if we have a kotlin/native version of skiko and logically it would not be very hard to realize it. Then we will have a foundation for true native desktop application with kotlin/native instead of going via jvm route using compose desktop. Is it really in the roadmap and if so, is there any tentative timeline for k/n version?

**Comment by sureshmaidaragi1919** [comment]
Still no plan? to support KMM :(

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-80">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
