### ISSUE TITLE
Replace dispatcherToBlockOn with Dispatchers.IO.limitedParallelism(...)

### ISSUE THREAD

**Issue by OliverO2** [JetBrains/skiko#823]
This seems no  longer accurate since Coroutines 1.6.0:
https://github.com/JetBrains/skiko/blob/4217f641562b060cca60be61bccaaf9b05cececc/skiko/src/awtMain/kotlin/org/jetbrains/skiko/redrawer/DispatcherToBlockOn.kt#L11-L12

There is now [Dispatchers.IO elasticity for limited parallelism](https://blog.jetbrains.com/kotlin/2021/12/introducing-kotlinx-coroutines-1-6-0/), which
* shares threads between all views of `Dispatchers.IO` and `Dispatchers.Default`,
* reduces context switching,
    > The withContext() invocation with Dispatchers.Default, Dispatchers.IO, or their views attempts not to switch threads when possible.
* creates daemon threads (not blocking application exit),
* but still avoids thread starvation by guaranteeing each view the requested parallelism. If necessary, threads are created beyond the 64-thread limit.

So it would probably be best to replace each invocation of `dispatcherToBlockOn` with `Dispatchers.IO.limitedParallelism(requiredParallelism)`.

**Comment by igordmn** [comment]
It was the first implementation, but we reverted it until it becomes stable.

It can't be used in Experimental state because we need to maintain backward compatibility between Kotlin and Skiko (to be me specific - between Kotlin and stable clients of Skiko such as Compose Multiplatform).

When it becomes stable, we can rewrite it to `limitedParallelism`.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-823">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
