### ISSUE TITLE
Bug: Cubic resampler results look very bad

### ISSUE THREAD

**Issue by StefanOltmann** [JetBrains/skiko#903]
I think there must be a error in the binding, because the results look pretty bad.

See https://issues.skia.org/issues/332580479

**Comment by elijah-semyonov** [comment]
Hi! I'll have a look.

**Comment by elijah-semyonov** [comment]
@StefanOltmann 
I've just checked upsampling behavior in order to identify whether there is an error in mapping of Kotlin values to Skia native ones.

Apparently, there is none, you can check it yourself in this branch
https://github.com/JetBrains/skiko/tree/es/bicubic-fix/samples/SkiaAwtSample

<img width="1313" alt="Screenshot 2024-04-05 at 11 08 41" src="https://github.com/JetBrains/skiko/assets/4167681/afaccfb9-cc87-49f0-bbb5-74d70b894cc0">

As far as I got it, you've got unsatisfying results during _downscaling_, so my guess is as a good, as Google pals': downsample kernel doesn't yield good result when the downscale magnitude is inadequate to Skia implementation assumptions about the usage.

I guess there is nothing I can do on our side.

**Comment by StefanOltmann** [comment]
@elijah-semyonov Thank you a lot for investigating this issue and making sure it's not a problem in the binding.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/SKIKO-903">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
